title: Dimiaun's Blog
author: Dimiaun
email: your-dimiaun@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my weely blog, where I keep you posted about the latest changes in ....

# social links
twitter_username: @Dimiaun
github_username:  Dimiaun

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
